/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 21/06/2019 00:49:43
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            40000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            8000000
#define MX_HSE_VALUE                            8000000
#define MX_HSI14_VALUE                          14000000
#define MX_HSI48_VALUE                          48000000
#define MX_PLLCLKFreq_Value                     16000000
#define MX_PLLMCOFreq_Value                     4000000
#define MX_SYSCLKFreq_VALUE                     48000000
#define MX_HCLKFreq_Value                       48000000
#define MX_MCOFreq_Value                        8000000
#define MX_FCLKCortexFreq_Value                 48000000
#define MX_TimSysFreq_Value                     48000000
#define MX_AHBFreq_Value                        48000000
#define MX_APB1Freq_Value                       48000000
#define MX_APB1TimFreq_Value                    48000000
#define MX_ADCoutputFreq_Value                  14000000
#define MX_FLITFCLKFreq_Value                   8000000
#define MX_CECFreq_Value                        32786
#define MX_I2C1Freq_Value                       8000000
#define MX_I2SFreq_Value                        48000000
#define MX_USART1Freq_Value                     48000000
#define MX_USART2Freq_Value                     48000000
#define MX_RTCFreq_Value                        40000
#define MX_RTCHSEDivFreq_Value                  250000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   40000
#define MX_VCOOutput2Freq_Value                 8000000

/*-------------------------------- ADC        --------------------------------*/

#define MX_ADC                                  1

/* GPIO Configuration */

/* Pin PA3 */
#define MX_ADC_IN3_Pin_Remapping                HAL_REMAP_PA11_PA12
#define MX_ADC_IN3_Pin                          PA3
#define MX_ADC_IN3_GPIOx                        GPIOA
#define MX_ADC_IN3_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN3_GPIO_Pin                     GPIO_PIN_3
#define MX_ADC_IN3_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA2 */
#define MX_ADC_IN2_Pin_Remapping                HAL_REMAP_PA11_PA12
#define MX_ADC_IN2_Pin                          PA2
#define MX_ADC_IN2_GPIOx                        GPIOA
#define MX_ADC_IN2_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN2_GPIO_Pin                     GPIO_PIN_2
#define MX_ADC_IN2_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA1 */
#define MX_ADC_IN1_Pin_Remapping                HAL_REMAP_PA11_PA12
#define MX_ADC_IN1_Pin                          PA1
#define MX_ADC_IN1_GPIOx                        GPIOA
#define MX_ADC_IN1_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN1_GPIO_Pin                     GPIO_PIN_1
#define MX_ADC_IN1_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA0 */
#define MX_ADC_IN0_Pin_Remapping                HAL_REMAP_PA11_PA12
#define MX_ADC_IN0_Pin                          PA0
#define MX_ADC_IN0_GPIOx                        GPIOA
#define MX_ADC_IN0_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN0_GPIO_Pin                     GPIO_PIN_0
#define MX_ADC_IN0_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA5 */
#define MX_ADC_IN5_Pin_Remapping                HAL_REMAP_PA11_PA12
#define MX_ADC_IN5_Pin                          PA5
#define MX_ADC_IN5_GPIOx                        GPIOA
#define MX_ADC_IN5_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN5_GPIO_Pin                     GPIO_PIN_5
#define MX_ADC_IN5_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA4 */
#define MX_ADC_IN4_Pin_Remapping                HAL_REMAP_PA11_PA12
#define MX_ADC_IN4_Pin                          PA4
#define MX_ADC_IN4_GPIOx                        GPIOA
#define MX_ADC_IN4_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN4_GPIO_Pin                     GPIO_PIN_4
#define MX_ADC_IN4_GPIO_Mode                    GPIO_MODE_ANALOG

/*-------------------------------- CAN        --------------------------------*/

#define MX_CAN                                  1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_CAN_RX_GPIO_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_CAN_RX_Pin_Remapping                 HAL_REMAP_PA11_PA12
#define MX_CAN_RX_Pin                           PA11
#define MX_CAN_RX_GPIOx                         GPIOA
#define MX_CAN_RX_GPIO_PuPd                     GPIO_NOPULL
#define MX_CAN_RX_GPIO_Pin                      GPIO_PIN_11
#define MX_CAN_RX_GPIO_AF                       GPIO_AF4_CAN
#define MX_CAN_RX_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_CAN_TX_GPIO_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_CAN_TX_Pin_Remapping                 HAL_REMAP_PA11_PA12
#define MX_CAN_TX_Pin                           PA12
#define MX_CAN_TX_GPIOx                         GPIOA
#define MX_CAN_TX_GPIO_PuPd                     GPIO_NOPULL
#define MX_CAN_TX_GPIO_Pin                      GPIO_PIN_12
#define MX_CAN_TX_GPIO_AF                       GPIO_AF4_CAN
#define MX_CAN_TX_GPIO_Mode                     GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC CEC_CAN_IRQn */
#define MX_CEC_CAN_IRQn_interruptPremptionPriority 0
#define MX_CEC_CAN_IRQn_Subriority              0

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Channel2_3_IRQn */
#define MX_DMA1_Channel2_3_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel2_3_IRQn_Subriority      0

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PF1-OSC_OUT */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_HIGH
#define MX_I2C1_SCL_Pin_Remapping               HAL_REMAP_PA11_PA12
#define MX_I2C1_SCL_Pin                         PF1_OSC_OUT
#define MX_I2C1_SCL_GPIOx                       GPIOF
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_1
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF1_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PF0-OSC_IN */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_HIGH
#define MX_I2C1_SDA_Pin_Remapping               HAL_REMAP_PA11_PA12
#define MX_I2C1_SDA_Pin                         PF0_OSC_IN
#define MX_I2C1_SDA_GPIOx                       GPIOF
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SMBA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_0
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF1_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* DMA Configuration */

/* DMA I2C1_TX */
#define MX_I2C1_TX_DMA_DMA_Handle               
#define MX_I2C1_TX_DMA_Instance                 DMA1_Channel2
#define MX_I2C1_TX_DMA_Priority                 DMA_PRIORITY_LOW
#define MX_I2C1_TX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_BYTE
#define MX_I2C1_TX_DMA_MemDataAlignment         DMA_MDATAALIGN_BYTE
#define MX_I2C1_TX_DMA_Mode                     DMA_NORMAL
#define MX_I2C1_TX_DMA_Direction                DMA_MEMORY_TO_PERIPH
#define MX_I2C1_TX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_I2C1_TX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_I2C1_TX_DMA_IpInstance               

/* DMA I2C1_RX */
#define MX_I2C1_RX_DMA_DMA_Handle               
#define MX_I2C1_RX_DMA_Instance                 DMA1_Channel3
#define MX_I2C1_RX_DMA_Priority                 DMA_PRIORITY_LOW
#define MX_I2C1_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_BYTE
#define MX_I2C1_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_BYTE
#define MX_I2C1_RX_DMA_Mode                     DMA_NORMAL
#define MX_I2C1_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_I2C1_RX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_I2C1_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_I2C1_RX_DMA_IpInstance               

/* NVIC Configuration */

/* NVIC I2C1_IRQn */
#define MX_I2C1_IRQn_interruptPremptionPriority 0
#define MX_I2C1_IRQn_Subriority                 0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA6 */
#define MX_PA6_Pin_Remapping                    HAL_REMAP_PA11_PA12
#define MX_PA6_Pin                              PA6
#define MX_PA6_GPIOx                            GPIOA
#define MX_PA6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA6_GPIO_Pin                         GPIO_PIN_6
#define MX_PA6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA7 */
#define MX_PA7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA7_Pin_Remapping                    HAL_REMAP_PA11_PA12
#define MX_PA7_Pin                              PA7
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_PinState                         GPIO_PIN_RESET
#define MX_PA7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7
#define MX_PA7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB1 */
#define MX_PB1_Pin_Remapping                    HAL_REMAP_PA11_PA12
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_Mode                        GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */
