/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 02/05/2019 22:24:01
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            40000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            8000000
#define MX_HSE_VALUE                            8000000
#define MX_HSI14_VALUE                          14000000
#define MX_HSI48_VALUE                          48000000
#define MX_PLLCLKFreq_Value                     16000000
#define MX_PLLMCOFreq_Value                     16000000
#define MX_SYSCLKFreq_VALUE                     48000000
#define MX_HCLKFreq_Value                       48000000
#define MX_MCOFreq_Value                        48000000
#define MX_FCLKCortexFreq_Value                 48000000
#define MX_TimSysFreq_Value                     48000000
#define MX_AHBFreq_Value                        48000000
#define MX_APB1Freq_Value                       48000000
#define MX_APB1TimFreq_Value                    48000000
#define MX_ADCoutputFreq_Value                  14000000
#define MX_FLITFCLKFreq_Value                   8000000
#define MX_CECFreq_Value                        32786
#define MX_I2C1Freq_Value                       8000000
#define MX_I2SFreq_Value                        48000000
#define MX_USART1Freq_Value                     48000000
#define MX_USART2Freq_Value                     48000000
#define MX_RTCFreq_Value                        40000
#define MX_RTCHSEDivFreq_Value                  250000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   40000
#define MX_VCOOutput2Freq_Value                 8000000

/*-------------------------------- CAN        --------------------------------*/

#define MX_CAN                                  1

/* GPIO Configuration */

/* Pin PB8 */
#define MX_CAN_RX_GPIO_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_CAN_RX_Pin                           PB8
#define MX_CAN_RX_GPIOx                         GPIOB
#define MX_CAN_RX_GPIO_PuPd                     GPIO_NOPULL
#define MX_CAN_RX_GPIO_Pin                      GPIO_PIN_8
#define MX_CAN_RX_GPIO_FM8                      __NULL
#define MX_CAN_RX_GPIO_AF                       GPIO_AF4_CAN
#define MX_CAN_RX_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PB9 */
#define MX_CAN_TX_GPIO_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_CAN_TX_Pin                           PB9
#define MX_CAN_TX_GPIOx                         GPIOB
#define MX_CAN_TX_GPIO_PuPd                     GPIO_NOPULL
#define MX_CAN_TX_GPIO_Pin                      GPIO_PIN_9
#define MX_CAN_TX_GPIO_AF                       GPIO_AF4_CAN
#define MX_CAN_TX_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_CAN_TX_GPIO_FM9                      __NULL

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USB        --------------------------------*/

#define MX_USB                                  1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_USB_DM_Pin                           PA11

/* Pin PA12 */
#define MX_USB_DP_Pin                           PA12

/* NVIC Configuration */

/* NVIC USB_IRQn */
#define MX_USB_IRQn_interruptPremptionPriority  0
#define MX_USB_IRQn_Subriority                  0

/*-------------------------------- USB_DEVICE --------------------------------*/

#define MX_USB_DEVICE                           1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */
